### ISSUE TITLE
Adding swiftlint

### ISSUE THREAD

**Issue by tami5** [creativenull/diagnosticls-configs-nvim#1]
Hey @creativenull,

I'm trying to add swiftlint to diagnosticls-nvim, however, it doesn't seem to be working as expected.

In my init.lua I had the following

```lua
require'diagnosticls-nvim'.init{}
require'diagnosticls-nvim'.setup{
  ['swift'] = {
    linter = {
      sourceName = 'swiftlint',
      command = "swiftlint",
      debounce = 100,
      args = {
        'lint',
        '--use-stdin',
        "--quiet",
        "--reporter",
        "json",
      },
      rootPatterns = {
        '.git',
      }
    }
  }
}
```

I tried to draw inspeeration from existing plugins in other editors like vscode: https://github.com/vknabel/vscode-swiftlint/blob/master/src/lint.ts

It would be awesome if you can point out why it didn't work for me or what I missed.

Thanks

**Comment by creativenull** [comment]
Hey!

Looks like the command line is outputting the results in a JSON format, you will have to parse it first so that the diagnostics can add it to nvim.

Take a look at the [eslint.lua](https://github.com/creativenull/diagnosticls-nvim/blob/82edbcc8124ceda6376276ae06dcf364727fdf8a/lua/diagnosticls-nvim/linters/eslint.lua) I added to the list, where there is a `parseJson` and a `securities` key with values in it.

If you don't know how to see the json format, then you can write the command out on the terminal, something like: `cat <filename> | swiftlint lint --use-stdin --quiet --reporter json`

I'll also see if I am able to parse it and add it to the list as well, when I get the time this weekend.

**Comment by jandamm** [comment]
I'm not sure if this plugin supports `errorformat`.
If it does you can copy the efm from my dotfiles:
https://github.com/jandamm/dotfiles/blob/main/nvim/.config/nvim/compiler/swiftlint.vim

**Comment by creativenull** [comment]
I'm not sure if the diagnostic language server supports it or not, it's not up to this plugin to support it. Whatever output comes from the linter, diagnosticls will just give the settings to parse the messages in the format it needs to interface with vim.

All I know is I can parse the messages as line by line via a RegEx string, or use `--reporter json` to get in a json format and parse it that way, and then specify what is an error, warning, hint, etc

I'll take a look and see how you've done it though, thanks!

**Comment by jandamm** [comment]
Well the regex of the errorformat should be something like this:

`([^:]+):(\d+):((\d+):)? (warning|error): (.*)`
Where you have file, line, column?, warning/error and message.
